name = "spin-macho-casino-gr"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spin-macho-casino.gr"
HMAC_KEY = "8530a4ce022c8d33461ae43f51c138687fc2bcac530554bc0685aa0f7b7843a6"
COOKIE_NAME = "xdx"
PLAY_PATH = "go"
BUTTON_ID = "p638733837059fa5bfc9b46166191ef60"
GATE_SALT = "4be5491352f20b90"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "3g1c"
CTA_SELECTOR = ".play-button"
