name = "spin-macho-casino-gr"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spin-macho-casino.gr"
HMAC_KEY = "8530a4ce022c8d33461ae43f51c138687fc2bcac530554bc0685aa0f7b7843a6"
COOKIE_NAME = "45v"
PLAY_PATH = "begin"
BUTTON_ID = "p638733837059fa5bfc9b46166191ef60"
GATE_SALT = "ff0fe3962df4b827"
